# Generated by Django 4.0.6 on 2022-07-21 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.SlugField(max_length=100, unique=True, verbose_name='id категории')),
                ('category_title', models.CharField(max_length=100, verbose_name='Название категорий')),
                ('category_photo', models.CharField(max_length=100, verbose_name='URL фото категорий')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tovar_id', models.SlugField(max_length=100, unique=True, verbose_name='id товара')),
                ('tovar_title', models.CharField(max_length=100, verbose_name='Название товара')),
                ('tovar_price', models.IntegerField(verbose_name='Цена товара')),
                ('tovar_discription', models.CharField(max_length=500, verbose_name='Описание')),
                ('tovar_photo', models.CharField(max_length=100, verbose_name='URL фото товара')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.categorycard', to_field='cat_id')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
